export const DELETE_BUDGET = 'DELETE_BUDGET';
export const SAVE_BUDGET = 'SAVE_BUDGET';
export const SET_ALL_BUDGETS = 'SET_ALL_BUDGETS';
export const SET_PASSCODE = 'SET_PASSCODE';
export const DATA_LOADED = 'DATA_LOADED';